# アクション名
name: Test codes
# タイミングを指定
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  Test:
    name: Run test codes
    if: |
      github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install packages
        run: npm ci

      - name: Show coverage
        run: npm run test:coverage -- --bail --maxWorkers=100% --watchAll=false
